/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, EffectFade, Navigation, Pagination } from 'swiper';
import "swiper/css/bundle";
import 'swiper/css';

const ab = ['/onas2.jpg', '/onas4.jpg', '/onas5.jpg']

export const HeroSection = () => {
  return (
    <div className="max-w-7xl">
      <section className="flex p-12">
        <div className='z-10 max-w-lg p-12 rounded-lg shadow-lg backdrop-blur-lg'>
          <div className="font-extrabold font-russo">
            <div className="text-7xl text-gbrown-400">GRIZZLY</div>
            <div className="text-4xl xl">Fight Club</div>
          </div>
          <div className="my-8">
            <span>Prowadzimy treningi</span>
            <span className='relative inline-block px-8 ml-2 overflow-hidden text-center align-bottom h-7'>
              <span className="absolute bottom-0 left-0 font-extrabold animate-switch-text text-gray-50">
                <div className='text-gteal-500'>judo</div>
                <div className='text-gbrown-200'>karate</div>
                <div className='text-gray-400'>baletu</div>
                <div className='text-red-400'>bjj</div>
              </span>
            </span>
            <span>, w kilkudziesięciu szkołach podstawowych i przedszkolach rozmieszczonych w całej Warszawie oraz jej obrzeżach.</span>
          </div>
            <a
              href="#"
              className="flex items-center justify-center px-8 py-3 text-lg font-bold text-white duration-200 ease-in border border-transparent rounded-lg bg-gteal-400 hover:bg-gteal-500"
            >
              Zapisy
            </a>
        </div>
        <div className='shadow-lg rotate-lg-6'>
          <Swiper
            effect="fade"
            navigation
            pagination
            autoplay
            modules={[Autoplay, EffectFade, Navigation, Pagination]}
            className='rounded-xl'
          >
            <SwiperSlide><img src='/onas2.jpg' alt=''/></SwiperSlide>
            <SwiperSlide><img src='/onas4.jpg' alt=''/></SwiperSlide>
            <SwiperSlide><img src='/onas5.jpg' alt=''/></SwiperSlide>
          </Swiper>

        </div>
        {/* <div className='relative -translate-x-4 translate-y-4 shadow-lg w-96 h-96 rotate-6'>
          <Image src="/baner.jpg" layout='fill' alt='image' className='rounded-lg'/>
        </div> */}
      </section>
    </div>
  )
}

const Home= () => {
  return (
    <div>
      <Head>
        <title>Grizzly Fight Club</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
    </div>
  )
}

export default Home
